version: '3.8'

services:
  mongo1:
    image: mongo:latest
    container_name: mongo1
    ports:
      - "27017:27017"
    networks:
      - mongo-network
    volumes:
      - mongo1-data:/data/db
    command: ["mongod", "--replSet", "rs0"]

  mongo2:
    image: mongo:latest
    container_name: mongo2
    networks:
      - mongo-network
    volumes:
      - mongo2-data:/data/db
    command: ["mongod", "--replSet", "rs0"]

  mongo3:
    image: mongo:latest
    container_name: mongo3
    networks:
      - mongo-network
    volumes:
      - mongo3-data:/data/db
    command: ["mongod", "--replSet", "rs0"]

networks:
  mongo-network:
    driver: bridge

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:
